Dang-Bun/DANGBUN-frontend

- src/components/PopUp/PopUpCard.tsx
- src/global.css
- src/pages/E/PlaceJoin1.tsx
- src/pages/E/PlaceJoin2.tsx
- src/router/Router.tsx
-[.] 기능 추가
-[.] 버그 수정
ex) D3 -> main
E001~004의 팝업 기능 구현 등을 실현함.
> Feat : E001~004 구현

- package.json
- src/assets/nav/arrowBack.svg
- src/components/HeaderBar.tsx
- src/pages/G/NotificationCreate.tsx
- src/pages/G/ViewPage.tsx
- yarn.lock
- 기능 추가
H -> main 
HeaderBar 구현
오른쪽 navigation은 viewPage 참고 
> Feat : HeaderBar 구현

- src/components/place/PlaceRollCard.tsx
- src/pages/D/PlaceMake1.tsx
-[] 버그 수정
ex) K->main
기능명세서에 따라 inputfiled의 글자 수 조정
.
> Fix : 기능명세서 반영 D001~003

- src/apis/axios.ts
- src/hooks/useUserApi.ts
- src/pages/A/LogIn.tsx
-[] 기능 추가
ex) login_api -> main
Login api 구현 & API 구현 기반 마련
> Login api 구현 & API 구현 기반 마련

- src/apis/user.ts
- src/components/PopUp/PopUpCard.tsx
- src/components/PopUp/RequestPopUp.tsx
- src/global.css
- src/pages/B/MyPlace.tsx
- src/pages/C/MyInfo.tsx
- src/pages/I/Setting.tsx
- src/router/Router.tsx
-[] 기능 추가
C -> main
C 내 정보 페이지 구현 완료 및 관련 API 연동(로그아웃/회원탈퇴/회원정보 조회)
> Feat: C 내 정보 페이지 구현 완료 및 관련 API 연동(로그아웃/회원탈퇴/회원정보 조회)

- src/components/place/GradRollCard.tsx
- src/components/place/PlaceRollCard.tsx
- src/pages/D/PlaceMake1.tsx
- src/pages/E/PlaceJoin2.tsx
-[*] 기능 추가
ex) place_api->main
D&E 완전 연결 끝
> Fix : 카테고리 아이콘 파트 적용 완료 & D/E API 연동 완전 끝

- src/pages/I/SettingManager.tsx
- src/pages/I/SettingMember.tsx
- src/pages/M/PlaceDetailed.tsx
- src/pages/N/DangerZoneManager.tsx
- src/pages/N/DangerZoneMember.tsx
- src/router/Router.tsx
-[] 기능 추가
I -> main
플레이스 세부 설정 UI 구현 완
> Feat: M 플레이스 세부 설정 구현 완료

- src/components/BottomBar.tsx
- src/components/PopUp/PopUpCardDanger.tsx
- src/hooks/useMemberApi.ts
- src/hooks/usePlaceApi.ts
- src/pages/B/MyPlace.tsx
- src/pages/D/PlaceMake3.tsx
- src/pages/F/Home.tsx
- src/pages/I/SettingMember.tsx
- src/pages/N/DangerZoneManager.tsx
- src/pages/N/DangerZoneMember.tsx
-[] 기능 추가
N -> main
N DangerZone 플레이스 나가기, 플레이스 삭제 기능 API 연동해서 추가
홈화면으로 라우팅하여 이제 거의 모든 페이지 navigate 연결 완료
> N DangerZone 플레이스 나가기, 플레이스 삭제 API 연동 및 홈화면과 navigate

- src/components/cleanUp/CleanUpCard.tsx
- src/components/cleanUp/DangbunList.tsx
- src/hooks/useCleaningApi.ts
- src/hooks/useDutyApi.ts
- src/pages/I/SettingManager.tsx
- src/pages/K/CleanAdd.tsx
- src/pages/K/CleanUpList.tsx
- src/pages/K/UnDangbun.tsx
- src/router/Router.tsx
-[] 기능 추가
ex) cleaning_api -> main
memeber routere 연결 + 파일 포함.
> Cleaning api

- src/components/PopUp/UpLoadPopUp.tsx
- src/components/calendar/DownloadPopUp.tsx
- src/components/home/TaskCard.tsx
- src/components/home/UpLoad.tsx
- src/global.css
- src/pages/F/ManagerHome.tsx
- src/pages/F/MemberHome.tsx
- src/pages/H/CalendarPage.tsx
- src/stores/Test/initialDuties.ts
- src/styles/CalendarPage.css
-기능 추가
f -> dev
- 캘린더 프로그래스바 구현 (H001)
- 캘린더 사진 다운로드 구현 (H008)
- 사진 업로드 팝업 구현 (F009)
> Feat : H001, H008, F009 UI 구현

- src/assets/checkIcon/selectedDangbun.svg
- src/assets/checkIcon/unselectedDangbun.svg
- src/hooks/useCleaningApi.ts
- src/hooks/useDutyApi.ts
- src/pages/I/SettingManager.tsx
- src/pages/J/AddClean.tsx
- src/pages/J/DutyManagement.tsx
- src/pages/J/ManagementManager.tsx
- src/pages/J/ModifyDuty.tsx
-[] 기능 추가
ex) J -> main
Feat: 당번 관리 페이지 당번 역할분담/청소 제외 기능 제외하고 모두 구현
> Feat: 당번 관리 페이지 당번 역할분담/청소 제외 기능 제외하고 모두 구현

- src/components/PopUp/PopUpCardDanger.tsx
- src/hooks/useMemberApi.ts
- src/pages/I/SettingMember.tsx
- src/pages/J/DutyManagement.tsx
- src/pages/J/DutyMember.tsx
- src/pages/J/ManagementMember.tsx
- src/pages/M/PlaceDetailed.tsx
- src/pages/N/DangerZoneManager.tsx
- src/router/Router.tsx
-[] 기능 추가
ex) M -> main
M DangerZone 맴버 목록 조회 및 맴버 추방 API 연동
> Feat: M DangerZone 맴버 목록 조회 및 맴버 추방 API 연동

- package-lock.json
- src/apis/axios.ts
- src/components/cleanUp/CleanUpCard.tsx
- src/components/cleanUp/DangbunList.tsx
- src/hooks/useCleaningApi.ts
- src/pages/K/CleanAdd.tsx
- src/pages/K/CleanEdit.tsx
- src/pages/K/CleanUpList.tsx
- src/pages/K/UnDangbun.tsx
- src/pages/L/ManagerInfo.tsx
- src/pages/L/MemberList.tsx
- yarn.lock
> Cleaning api 연결 및 90% 마무리

- src/apis/axios.ts
- src/components/BottomBar.tsx
- src/components/calendar/CalendarTaskCard.tsx
- src/components/calendar/DownloadPopUp.tsx
- src/components/home/CircularProgressBar.tsx
- src/components/home/PlaceNameCard.tsx
- src/components/home/PlaceProgressCard.tsx
- src/components/home/TaskCard.tsx
- src/components/notification/NotificationCard.tsx
- src/components/notification/NotificationTab.tsx
- src/components/notification/SearchModal.tsx
- src/components/notification/WritingChip.tsx
- src/features/checklist/actions.ts
- src/hooks/useCalendarApi.ts
- src/hooks/useChecklistApi.ts
- src/hooks/useNotificationApi.ts
- src/pages/B/MyPlace.tsx
- src/pages/F/Home.tsx
- src/pages/F/ManagerHome.tsx
- src/pages/F/ManagerOverview.tsx
- src/pages/F/MemberHome.tsx
- src/pages/G/Notification.tsx
- src/pages/G/NotificationCreate.tsx
- src/pages/G/NotificationDetail.tsx
- src/pages/H/CalendarDetail.tsx
- src/pages/H/CalendarPage.tsx
- src/router/Router.tsx
-[] 기능 추가
ex) f-> dev
홈 api 연동, 알림함 수정, 캘린더 페이지 api 구현중
> Feat : 홈화면 api 연동

- src/apis/axios.ts
- src/components/cleanUp/DangbunList.tsx
- src/hooks/usePlaceApi.ts
- src/pages/A/Join.tsx
- src/pages/L/EnterCode.tsx
- src/pages/L/ManagerInfo.tsx
-[] 기능 추가
M -> main
참여코드 API 연동 및 이미지 경로 수정
> Feat: 참여코드 API 연동 및 이미지 경로 수정

- src/pages/B/MyPlace.tsx
> Feat: 수락대기 시 경로 수정

- src/pages/F/MemberHome.tsx
> Fix: 배포 빌드 수정

- src/components/notification/NotificationCard.tsx
- src/components/notification/SearchModal.tsx
- src/hooks/useNotificationApi.ts
- src/pages/F/ManagerHome.tsx
- src/pages/F/MemberHome.tsx
- src/pages/G/Notification.tsx
- src/pages/G/NotificationCreate.tsx
- src/pages/G/NotificationDetail.tsx
- yarn.lock
1. 알림전송 후, 받은 알림 표시 문제
+읽음처리
2. 보내는 사람 중복 선택 불가능으로 수정
3. 멤버 검색  
4. 보내는 사람 혼합 가능
5. api 연결 보강
6. 알림함 뒤로가기 삭제
> Fix : 알림함 QA 반영

- src/pages/F/ManagerHome.tsx
- src/pages/G/Notification.tsx
- src/pages/H/CalendarPage.tsx
-[] 기능 추가
HomeAPI -> dev
배포 빌드 에러 수정
homeapi 연동 중`
> Fix : 배포 빌드 수정 및 캘린더 api 연동 수정 중

- src/pages/B/MyPlace.tsx
- src/pages/I/SettingMember.tsx
- src/pages/J/DutyMember.tsx
> 멤버 설정에서 당번 관리 문제 해결

- src/pages/K/CleanAdd.tsx
> Fix : 날짜 선택 이슈 변경

- src/components/calendar/CalendarTaskCard.tsx
- src/components/home/BlueChip.tsx
- src/components/home/CircularProgressBar.tsx
- src/pages/F/ManagerHome.tsx
- src/pages/F/MemberHome.tsx
- src/pages/G/Notification.tsx
- src/pages/H/CalendarPage.tsx
> Feat : HomeAPI QA 반영..

- src/components/cleanUp/CleanUpCard.tsx
- src/pages/K/CleanUpList.tsx
> Fix : 청소관리에 개수를 당번->청소로 수정

- src/pages/J/DutyManagement.tsx
- src/pages/J/DutyMember.tsx
> Fix: 당번에 배정만 청소에 배정 가능하게 변경

- src/pages/Home/MemberHome.tsx
> Fix : 스크롤 수정

- src/components/calendar/CalendarTaskCard.tsx
- src/components/home/CleaningDeletePopUp.tsx
- src/pages/Calendar/CalendarPage.tsx
- src/pages/Home/ManagerHome.tsx
> Feat : 삭제 기능 추가 및 스크롤 문제 해결

- src/components/cleanUp/CleanUpCard.tsx
- src/pages/Cleaning/UnDangbun.tsx
> Qa dohyeon

- src/components/cleanUp/CleanUpCard.tsx
- src/pages/Cleaning/CleanUpList.tsx
> fix :css 수정

- src/pages/Home/ManagerHome.tsx
- src/pages/Home/MemberHome.tsx
> HotFix!: 홈화면 스크롤 문제 해결

- src/features/checklist/actions.ts
- src/pages/Home/ManagerHome.tsx
> Fix: 배포 오류 fix

- src/pages/Home/ManagerHome.tsx
- src/pages/Home/MemberHome.tsx
> Design : 필터 섹션 bg 삭제제
